#**NUMPY BASICS**

#CREATING A NUMPY ARRAY

In [ ]:
import numpy as np

# a = [ ]
a = [2,5,8,9]
# array = np.array(a)
array = np.array(5)
print(array)


5


In [ ]:
one_d_numpy_array = np.array([2,5,8,9])
print(one_d_numpy_array)

[2 5 8 9]


In [ ]:
zero_d_numpy_array = np.array(5)
print(zero_d_numpy_array)

5


In [ ]:
#Code to find the dimension of defined array
print(one_d_numpy_array.ndim)
print(zero_d_numpy_array.ndim)

1
0


In [ ]:
arr = [[1,2,3,4], [4,5,6,7]]
two_dimensional_array = np.array(arr)
print(two_dimensional_array.ndim)

2


In [ ]:
arr = [[1,2,3],[3,4,5],[5,6,7]]
three_dimensional_array = np.array(arr)
print(three_dimensional_array)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [ ]:
#Creating array and its attributes
a = [[2,4,6,8],[3,5,7,9]]   #Creating a list named "a"
arr = np.array(a)       #Converting the list into numpy array
print(arr)
print(arr.shape)     #Creating the shape of array e.g: 2*4 = 2 rows, 4 columns
print(arr.ndim)       #Printing array dimension
print(arr.dtype)      #array data types
print(arr.size)
print(arr.itemsize)

[[2 4 6 8]
 [3 5 7 9]]
(2, 4)
2
int64
8
8


#ACCESSING NUMPY ARRAY INDEXES

In [ ]:
arr = np.array([3,5,7,9,11])
print(arr[0])       #Printing first index array
print(arr[1:3])     #Slicing array
print(arr[2]+arr[1])

3
[5 7]
12


In [ ]:
arr_2d = np.array([[1,2,3,4],[6,7,8,9]])
print(arr_2d[1,1])

7


In [ ]:
arr_3d = np.array([[[1,2,3],[3,2,1]]
                   ,[[4,5,6],[7,8,9]]])
print(arr_3d[1,1,1])

8


#NEGATIVING INDEXING

In [ ]:
arr_3d = np.array([[[1,2,3],[3,2,1]]
                   ,[[4,5,6],[7,8,9]]])
print(arr_3d[1,1,-1])

9


#SLICING IN NUMPY_ARRAY

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([[2,4,6,8,11],[1,3,5,7,9]])
print(arr[0, 1:-2])

[4 6]


#HOMEWORK

#Create a numpy array from the list [7,14,21,28]. Print the array

In [ ]:
arr = np.array([7,14,21,28])
print(arr)

[ 7 14 21 28]


#Create a 2D Numpy array[[5,10,15],[20,25,30]]. Print its shape and number of dimensions using array.ndim.

In [ ]:
arr = np.array([[5,10,15],[20,25,30]])
print(arr.ndim)
print(arr.shape)

2
(2, 3)


In [ ]:
arr = np.zeros((2,3))
arr1 = np.arange(0,12)
print(arr)
print(arr1[0:13:3])

[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]


In [ ]:
arr = np.array([2,4,6,8])
mul = arr * 3
print(mul)

[ 6 12 18 24]


In [ ]:
arr = np.array([1,3,5,7,9,11])
print(arr[2])
print(arr[1:3])

5
[3 5]
